### ISSUE TITLE
Documentation to run

### ISSUE THREAD

**Issue by PranayRaman** [NBA-Betting/NBA_Betting#51]
please include docs to run

**Comment by MarKaliGG** [comment]
we need your help!!

**Comment by MarKaliGG** [comment]
Im stuck whit the installation too

**Comment by ard033** [comment]
permission denied when running src/deployment - why is that?

**Comment by jeffjohannsen** [comment]
Hmm, let me look at that when I get home tonight. I probably didn't update the Flask login info.

**Comment by ard033** [comment]
Any update on this? Is there somewhere we need to login to?

**Comment by jasonnan1** [comment]
When I run the python web_app.py command, I get the following error：
Traceback (most recent call last):
  File "/home/nan/NBA_Betting-main/src/deployment/web_app/nba_app.py", line 486, in <module>
    private_app = init_private_dashboard(app)
  File "/home/nan/NBA_Betting-main/src/deployment/dashboard/private_dashboard.py", line 43, in init_private_dashboard
    df = get_dashboard_data(connection)
  File "/home/nan/NBA_Betting-main/src/deployment/dashboard/private_dashboard.py", line 265, in get_dashboard_data
    df["game_datetime"]
  File "/home/nan/miniconda3/envs/nba/lib/python3.9/site-packages/pandas/core/generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
  File "/home/nan/miniconda3/envs/nba/lib/python3.9/site-packages/pandas/core/accessor.py", line 182, in __get__
    accessor_obj = self._accessor(obj)
  File "/home/nan/miniconda3/envs/nba/lib/python3.9/site-packages/pandas/core/indexes/accessors.py", line 512, in __new__
    raise AttributeError("Can only use .dt accessor with datetimelike values")
AttributeError: Can only use .dt accessor with datetimelike values
Why is this happening, my .env file is already configured correctly
